# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BMS Library
email: Horie.lunaticrave@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://horieyuuka.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: HorieYuuka
repository: HorieYuuka/horieyuuka.github.io

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

  # External navigation links
nav_external_links:
  - title: Sabuns
    url: https://drive.google.com/drive/folders/1OhnvhNbHrAftB2t1O6X8UESUSN4JCObj?usp=sharing
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: Report issues
    url: https://github.com/HorieYuuka/HorieYuuka.github.io/issues
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: IIDX.org
    url: https://iidx.org
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

      
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  Co-with:
    title: Compatible with
    color: purple
  warning:
    title: Warning
    color: red

sass:
    sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
